sudo: required

language: python

services:
  - docker

env:
  global:
    - DOCKER_UPLOAD="TRUE"

  matrix:

    - CLANG_VERSIONS="3.8"
    - CLANG_VERSIONS="3.9"
    - CLANG_VERSIONS="4.0"
    - GCC_VERSIONS="4.6"
    - GCC_VERSIONS="4.8"
    - GCC_VERSIONS="4.9"
    - GCC_VERSIONS="5.2"
    - GCC_VERSIONS="5.3"
    - GCC_VERSIONS="5.4"
    - GCC_VERSIONS="6.2"
    - GCC_VERSIONS="6.3"
    - GCC_VERSIONS="7.1"

script:
  - python build.py
